export function createElements() {
  return {
    loadScreen: document.getElementById("load-screen"),
    appScreen: document.getElementById("app-screen"),
    loadModelButton: document.getElementById("load-model-button"),
    loadModelLabel: document.getElementById("load-model-label"),
    compatibilityNote: document.getElementById("compatibility-note"),
    promptPanel: document.getElementById("prompt-panel"),
    togglePromptButton: document.getElementById("toggle-prompt-button"),
    scenarioSummary: document.getElementById("scenario-summary"),
    bootModelName: document.getElementById("boot-model-name"),
    bootModelDevice: document.getElementById("boot-model-device"),
    modelChipName: document.getElementById("model-chip-name"),
    modelChipDetail: document.getElementById("model-chip-detail"),
    progressMeter: document.getElementById("progress-meter"),
    progressMeterFill: document.getElementById("progress-meter-fill"), /* may be null after redesign */
    canvas: document.getElementById("world-canvas"),
    scenarioInput: document.getElementById("scenario-input"),
    generateButton: document.getElementById("generate-button"),
    worldCaption: document.getElementById("world-caption"),
    tickCount: document.getElementById("tick-count"),
    tokenCount: document.getElementById("token-count"),
    localStatus: document.getElementById("local-status"),
    networkStatus: document.getElementById("network-status"),
    convoStatusCard: document.getElementById("convo-status-card"),
    convoStatusText: document.getElementById("convo-status-text"),
    modelStatus: document.getElementById("model-status"),
    modelDetails: document.getElementById("model-details"),
    progressBar: document.getElementById("progress-bar-fill"),
    pauseButton: document.getElementById("pause-button"),
    playButton: document.getElementById("play-button"),
    fastButton: document.getElementById("fast-button"),
    screenshotButton: document.getElementById("screenshot-button"),
    logLatestButton: document.getElementById("log-latest-button"),
    logFullButton: document.getElementById("log-full-button"),
    inspectorEmpty: document.getElementById("inspector-empty"),
    inspectorContent: document.getElementById("inspector-content"),
    agentBadge: document.getElementById("agent-badge"),
    agentName: document.getElementById("agent-name"),
    agentRole: document.getElementById("agent-role"),
    agentStatusCard: document.getElementById("agent-status-card"),
    agentFocusCard: document.getElementById("agent-focus-card"),
    agentPressureCard: document.getElementById("agent-pressure-card"),
    agentStatus: document.getElementById("agent-status"),
    agentStatusDetail: document.getElementById("agent-status-detail"),
    agentGoalTitle: document.getElementById("agent-goal-title"),
    agentPressureTitle: document.getElementById("agent-pressure-title"),
    agentThought: document.getElementById("agent-thought"),
    agentGoal: document.getElementById("agent-goal"),
    agentPersonality: document.getElementById("agent-personality"),
    agentSecret: document.getElementById("agent-secret"),
    agentSpeechSection: document.getElementById("agent-speech-section"),
    agentSpeech: document.getElementById("agent-speech"),
    officeInput: document.getElementById("office-input"),
    officeSendButton: document.getElementById("office-send-button"),
    agentDebugPanel: document.getElementById("agent-debug-panel"),
    agentDiagnostics: document.getElementById("agent-diagnostics"),
    relationshipList: document.getElementById("relationship-list"),
    memoryList: document.getElementById("memory-list"),
    telemetryModelSummary: document.getElementById("telemetry-model-summary"),
    telemetryModelDetail: document.getElementById("telemetry-model-detail"),
    telemetryRuntimeSummary: document.getElementById("telemetry-runtime-summary"),
    telemetryRuntimeDetail: document.getElementById("telemetry-runtime-detail"),
    telemetryConversationSummary: document.getElementById("telemetry-conversation-summary"),
    telemetryConversationDetail: document.getElementById("telemetry-conversation-detail"),
    telemetryActiveSceneCard: document.getElementById("telemetry-active-scene-card"),
    telemetryActiveSceneTitle: document.getElementById("telemetry-active-scene-title"),
    telemetryActiveSceneDetail: document.getElementById("telemetry-active-scene-detail"),
    telemetryReflectionCount: document.getElementById("telemetry-reflection-count"),
    telemetryReflectionLatency: document.getElementById("telemetry-reflection-latency"),
    telemetryConversationCount: document.getElementById("telemetry-conversation-count"),
    telemetryConversationLatency: document.getElementById("telemetry-conversation-latency"),
    telemetryMemoryCount: document.getElementById("telemetry-memory-count"),
    telemetryMemoryLatency: document.getElementById("telemetry-memory-latency"),
    telemetryRepeatCount: document.getElementById("telemetry-repeat-count"),
    telemetryErrorCount: document.getElementById("telemetry-error-count"),
    telemetryLiveSpeaker: document.getElementById("telemetry-live-speaker"),
    telemetryLiveText: document.getElementById("telemetry-live-text"),
    telemetryDebugPanel: document.getElementById("telemetry-debug-panel"),
    promptTraceStream: document.getElementById("prompt-trace-stream"),
    telemetryStream: document.getElementById("telemetry-stream"),
    conversationLog: document.getElementById("conversation-log"),
    template: document.getElementById("log-entry-template")
  };
}

export function createContext(elements) {
  return elements.canvas.getContext("2d");
}

export function createWorkers() {
  return {
    reasoning: new Worker(new URL("./workers/reasoning-worker.js", import.meta.url), { type: "module" })
  };
}
